# replace default config

# multipass: true
# full: true

plugins:
    - removeDoctype: false
    - removeXMLProcInst: false
    - removeComments: false
    - removeMetadata: false
    - removeXMLNS: false
    - removeEditorsNSData: false
    - cleanupAttrs: true
    - inlineStyles: true
    - minifyStyles: false
    - convertStyleToAttrs: true
    - cleanupIDs: false
    - prefixIds: false
    - removeRasterImages: false
    - removeUselessDefs: true
    - cleanupNumericValues: false
    - cleanupListOfValues: false
    - convertColors: false
    - removeUnknownsAndDefaults: false
    - removeNonInheritableGroupAttrs: false
    - removeUselessStrokeAndFill: true
    - removeViewBox: false
    - cleanupEnableBackground: false
    - removeHiddenElems: false
    - removeEmptyText: false
    - convertShapeToPath: false
    - convertEllipseToCircle: false
    - moveElemsAttrsToGroup: false
    - moveGroupAttrsToElems: false
    - collapseGroups: true
    - convertPathData: false
    - convertTransform: false
    - removeEmptyAttrs: true
    - removeEmptyContainers: true
    - mergePaths: false
    - removeUnusedNS: false
    - sortAttrs: true
    - sortDefsChildren: false
    - removeTitle: false
    - removeDesc: false
    - removeDimensions: false
    - removeAttrs:
          attrs:
              - 'fill'
              - 'stroke'
              - 'fill-rule'
    - removeAttributesBySelector: false
    - removeElementsByAttr: false
    - addClassesToSVGElement: false
    - removeStyleElement: true
    - removeScriptElement: false
    - addAttributesToSVGElement: false
    - removeOffCanvasPaths: false
    - reusePaths: false

js2svg:
    pretty: true
    indent: '    '
